on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install qgis-plugin-ci
      run: pip3 install qgis-plugin-ci
    - name: Package plugin
      run: qgis-plugin-ci package dev
    - uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: '*.zip'
